name: "Generate README.md"
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate README.md
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Generate README.md
        uses: slattman/readme-generator@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: "slattman"
      - name: Archive README.md
        uses: actions/upload-artifact@v4
        with:
          name: readme
          path: README.md