name: generate-my-favorite-readme
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate-readme:
    uses: slattman/my-favorite-readme-generator/.github/workflows/my-favorite-readme-generator.yaml@main
    permissions: write-all
